components {
  id: "hero"
  component: "/main/runner_stan-main/hero/hero.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"Goose1\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
    "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/runner_stan-main/hero/hero.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"hero\"\n"
  "mask: \"geometry\"\n"
  "mask: \"danger\"\n"
  "mask: \"pickup\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 3.0\n"
  "      y: 194.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"Box\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: -35.0\n"
  "      y: 527.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 3\n"
  "    count: 1\n"
  "    id: \"Sphere\"\n"
  "  }\n"
  "  data: 124.283424\n"
  "  data: 202.49582\n"
  "  data: 11.887949\n"
  "  data: 148.89244\n"
  "}\n"
  ""
}
